# docker-compose.alt-ports.dev.yml
# Alternative port configuration for local development and debugging
# Uses different ports to avoid conflicts with existing services

services:
  postgres:
    container_name: airweave-db-alt
    image: postgres:16
    environment:
      POSTGRES_DB: airweave
      POSTGRES_USER: airweave
      POSTGRES_PASSWORD: airweave1234!
    command:
      - "postgres"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "shared_buffers=256MB"
      - "-c"
      - "effective_cache_size=1GB"
    ports:
      - "5435:5432"
    volumes:
      - postgres_data_alt:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U airweave" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    container_name: airweave-redis-alt
    image: redis:7-alpine
    ports:
      - "6381:6379"
    volumes:
      - redis_data_alt:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  text2vec-transformers:
    container_name: airweave-embeddings-alt
    image: semitechnologies/transformers-inference:sentence-transformers-all-MiniLM-L6-v2
    ports:
      - "9880:8080"
    environment:
      ENABLE_CUDA: 0
      WORKERS_PER_NODE: 1
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8080/health" ]
      interval: 5s
      timeout: 10s
      retries: 3
    restart: on-failure

  qdrant:
    container_name: airweave-qdrant-alt
    image: qdrant/qdrant:latest
    command: bash -c "apt-get update && apt-get install -y curl && ./entrypoint.sh" # we need to install curl to check health
    ports:
      - "6335:6333"
    volumes:
      - qdrant_data_alt:/qdrant/storage
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:6333/healthz" ]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: on-failure

  temporal:
    container_name: airweave-temporal-alt
    image: temporalio/auto-setup:1.24.2
    ports:
      - "7235:7233"
      - "8235:8233"
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=airweave
      - POSTGRES_PWD=airweave1234!
      - POSTGRES_SEEDS=postgres
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
    volumes:
      - ./temporal-config:/etc/temporal/config/dynamicconfig
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "tctl", "--address", "temporal:7233", "workflow", "list" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: on-failure

  temporal-ui:
    container_name: airweave-temporal-ui-alt
    image: temporalio/ui:2.26.2
    ports:
      - "8090:8080"
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    depends_on:
      temporal:
        condition: service_healthy
    restart: on-failure

volumes:
  postgres_data_alt:
  redis_data_alt:
  qdrant_data_alt:
